## 1. Import des bibliotheques

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import matplotlib.pyplot as plt
import folium
from sklearn.model_selection import train_test_split

## 2. Charger les datasets

In [6]:
df_a = pd.read_csv("Arkansas/Arkansas_full_clean.csv")
df_c =pd.read_csv("california/California_combined_cleaned.csv")

## 3. Explanatory data analysis

In [7]:
#l'Arkansas
df_a.info()
df_a.head()

<class 'pandas.DataFrame'>
RangeIndex: 9218 entries, 0 to 9217
Columns: 364 entries, B11_T0 to crop_name
dtypes: float64(362), int64(1), str(1)
memory usage: 25.6 MB

,B11_T0,B11_T1,B11_T10,B11_T11,B11_T12,B11_T13,B11_T14,B11_T15,B11_T16,B11_T17,...,B8_T4,B8_T5,B8_T6,B8_T7,B8_T8,B8_T9,crop_label,latitude,longitude,crop_name
0,3758.0,4060.0,6824.0,4118.0,5594.0,5586.0,6487.0,0.0,4378.0,3828.5,...,0.0,7660.0,2674.0,3207.0,3220.0,3489.0,5,34.403047,-91.417880,Soybeans
1,3185.5,3591.5,6134.0,3803.0,6019.5,5473.0,5635.5,3500.5,2872.0,2611.0,...,0.0,8188.0,2975.0,3567.0,3024.0,2976.0,1,34.296665,-91.354877,Corn
2,3063.0,3285.5,3038.0,2816.5,2981.0,3013.5,3468.0,0.0,3210.5,3494.0,...,9956.0,4626.0,2666.0,3808.0,3793.0,3913.0,5,34.327085,-91.512739,Soybeans
3,2196.0,3534.0,5513.5,3020.0,3690.5,5059.0,6081.5,0.0,5417.0,1875.0,...,0.0,3579.0,2370.0,2834.0,3135.0,4868.0,3,35.744828,-90.708118,Rice
4,3268.0,3586.0,4803.0,3734.5,0.0,0.0,4277.0,0.0,5297.0,6177.5,...,0.0,3162.0,2406.0,0.0,3542.0,3498.0,2,35.681737,-90.577141,Cotton

In [8]:
#ordonner les colonnes
nouvel_ordre = [
    'B2_T0','B3_T0','B4_T0','B5_T0','B6_T0','B7_T0','B8_T0','B8A_T0','B11_T0','B12_T0',
    'B2_T1','B3_T1','B4_T1','B5_T1','B6_T1','B7_T1','B8_T1','B8A_T1','B11_T1','B12_T1',
    'B2_T2','B3_T2','B4_T2','B5_T2','B6_T2','B7_T2','B8_T2','B8A_T2','B11_T2','B12_T2',
    'B2_T3','B3_T3','B4_T3','B5_T3','B6_T3','B7_T3','B8_T3','B8A_T3','B11_T3','B12_T3',
    'B2_T4','B3_T4','B4_T4','B5_T4','B6_T4','B7_T4','B8_T4','B8A_T4','B11_T4','B12_T4',
    'B2_T5','B3_T5','B4_T5','B5_T5','B6_T5','B7_T5','B8_T5','B8A_T5','B11_T5','B12_T5',
    'B2_T6','B3_T6','B4_T6','B5_T6','B6_T6','B7_T6','B8_T6','B8A_T6','B11_T6','B12_T6',
    'B2_T7','B3_T7','B4_T7','B5_T7','B6_T7','B7_T7','B8_T7','B8A_T7','B11_T7','B12_T7',
    'B2_T8','B3_T8','B4_T8','B5_T8','B6_T8','B7_T8','B8_T8','B8A_T8','B11_T8','B12_T8',
    'B2_T9','B3_T9','B4_T9','B5_T9','B6_T9','B7_T9','B8_T9','B8A_T9','B11_T9','B12_T9',
    'B2_T10','B3_T10','B4_T10','B5_T10','B6_T10','B7_T10','B8_T10','B8A_T10','B11_T10','B12_T10',
    'B2_T11','B3_T11','B4_T11','B5_T11','B6_T11','B7_T11','B8_T11','B8A_T11','B11_T11','B12_T11',
    'B2_T12','B3_T12','B4_T12','B5_T12','B6_T12','B7_T12','B8_T12','B8A_T12','B11_T12','B12_T12',
    'B2_T13','B3_T13','B4_T13','B5_T13','B6_T13','B7_T13','B8_T13','B8A_T13','B11_T13','B12_T13',
    'B2_T14','B3_T14','B4_T14','B5_T14','B6_T14','B7_T14','B8_T14','B8A_T14','B11_T14','B12_T14',
    'B2_T15','B3_T15','B4_T15','B5_T15','B6_T15','B7_T15','B8_T15','B8A_T15','B11_T15','B12_T15',
    'B2_T16','B3_T16','B4_T16','B5_T16','B6_T16','B7_T16','B8_T16','B8A_T16','B11_T16','B12_T16',
    'B2_T17','B3_T17','B4_T17','B5_T17','B6_T17','B7_T17','B8_T17','B8A_T17','B11_T17','B12_T17',
    'B2_T18','B3_T18','B4_T18','B5_T18','B6_T18','B7_T18','B8_T18','B8A_T18','B11_T18','B12_T18',
    'B2_T19','B3_T19','B4_T19','B5_T19','B6_T19','B7_T19','B8_T19','B8A_T19','B11_T19','B12_T19',
    'B2_T20','B3_T20','B4_T20','B5_T20','B6_T20','B7_T20','B8_T20','B8A_T20','B11_T20','B12_T20',
    'B2_T21','B3_T21','B4_T21','B5_T21','B6_T21','B7_T21','B8_T21','B8A_T21','B11_T21','B12_T21',
    'B2_T22','B3_T22','B4_T22','B5_T22','B6_T22','B7_T22','B8_T22','B8A_T22','B11_T22','B12_T22',
    'B2_T23','B3_T23','B4_T23','B5_T23','B6_T23','B7_T23','B8_T23','B8A_T23','B11_T23','B12_T23',
    'B2_T24','B3_T24','B4_T24','B5_T24','B6_T24','B7_T24','B8_T24','B8A_T24','B11_T24','B12_T24',
    'B2_T25','B3_T25','B4_T25','B5_T25','B6_T25','B7_T25','B8_T25','B8A_T25','B11_T25','B12_T25',
    'B2_T26','B3_T26','B4_T26','B5_T26','B6_T26','B7_T26','B8_T26','B8A_T26','B11_T26','B12_T26',
    'B2_T27','B3_T27','B4_T27','B5_T27','B6_T27','B7_T27','B8_T27','B8A_T27','B11_T27','B12_T27',
    'B2_T28','B3_T28','B4_T28','B5_T28','B6_T28','B7_T28','B8_T28','B8A_T28','B11_T28','B12_T28',
    'B2_T29','B3_T29','B4_T29','B5_T29','B6_T29','B7_T29','B8_T29','B8A_T29','B11_T29','B12_T29',
    'B2_T30','B3_T30','B4_T30','B5_T30','B6_T30','B7_T30','B8_T30','B8A_T30','B11_T30','B12_T30',
    'B2_T31','B3_T31','B4_T31','B5_T31','B6_T31','B7_T31','B8_T31','B8A_T31','B11_T31','B12_T31',
    'B2_T32','B3_T32','B4_T32','B5_T32','B6_T32','B7_T32','B8_T32','B8A_T32','B11_T32','B12_T32',
    'B2_T33','B3_T33','B4_T33','B5_T33','B6_T33','B7_T33','B8_T33','B8A_T33','B11_T33','B12_T33',
    'B2_T34','B3_T34','B4_T34','B5_T34','B6_T34','B7_T34','B8_T34','B8A_T34','B11_T34','B12_T34',
    'B2_T35','B3_T35','B4_T35','B5_T35','B6_T35','B7_T35','B8_T35','B8A_T35','B11_T35','B12_T35',
    'crop_label','latitude','longitude','crop_name'
]
df_a=df_a[nouvel_ordre]

In [9]:
df_a.head()

,B2_T0,B3_T0,B4_T0,B5_T0,B6_T0,B7_T0,B8_T0,B8A_T0,B11_T0,B12_T0,...,B6_T35,B7_T35,B8_T35,B8A_T35,B11_T35,B12_T35,crop_label,latitude,longitude,crop_name
0,1836.0,2042.0,2412.0,2616.0,2753.0,2920.0,3186.0,3215.0,3758.0,3099.0,...,2751.0,2963.0,3288.0,3227.0,3578.0,2796.0,5,34.403047,-91.417880,Soybeans
1,1647.0,1908.0,2099.0,2438.0,2752.0,2925.5,3122.0,3092.0,3185.5,2471.0,...,2733.0,2877.0,3073.0,3093.5,2923.5,2274.0,1,34.296665,-91.354877,Corn
2,1655.0,1878.5,2135.0,2279.5,2724.5,2947.5,3587.0,3190.0,3063.0,2307.0,...,2812.0,3246.5,4146.0,3495.5,3018.5,2285.0,5,34.327085,-91.512739,Soybeans
3,1817.5,1984.0,2207.0,2458.5,2499.5,2613.0,2731.0,2754.5,2196.0,1753.5,...,2695.0,2776.5,2809.0,3044.5,2978.5,2389.0,3,35.744828,-90.708118,Rice
4,1456.0,1630.0,1704.0,2031.0,2475.0,2684.0,3062.0,2971.0,3268.0,2510.0,...,3399.0,3661.0,4022.0,3991.0,3389.0,2462.0,2,35.681737,-90.577141,Cotton

In [10]:
df_a['crop_name'].value_counts()

crop_name
Soybeans    4873
Rice        1743
Corn        1623
Cotton       730
Others       249
Name: count, dtype: int64

In [11]:
map = folium.Map(location=[df_a['latitude'].mean(), df_a['longitude'].mean()], zoom_start=10)
for i in range(len(df_a)):
    folium.CircleMarker(
        location=[df_a.iloc[i]['latitude'],df_a.iloc[i]['longitude']],
        radius=2
    ).add_to(map)

map.save("map.html")

# 3.Le modele

## 3.1 L'arkansas

In [12]:
#separer x et y
X_a = df_a.drop(columns=['crop_label','latitude','longitude','crop_name']).values
y_a =df_a['crop_label'].values

In [13]:
#reshape
X_a = X_a.reshape(-1,36,10)

#normalisation
X_a = X_a / np.max(X_a)

In [14]:
#separer le dataset en :une partie pour entrainer et valider et une partie pour tester le modele
X_a_train, X_a_test, y_a_train, y_a_test = train_test_split(X_a, y_a, test_size=0.15, random_state=42)

In [ ]:
mask = (X_a_train != 0).astype(float)

In [15]:

#Le CNN
def CNNBlock(x):
    shortcut = x
    
    x = layers.Conv1D(filters=x.shape[-1], kernel_size=3, padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    x = layers.Conv1D(filters=x.shape[-1], kernel_size=3, padding='same')(x)
    x = layers.BatchNormalization()(x)

    x = layers.Add()([x, shortcut])  # skip connection
    x = layers.ReLU()(x)

    return x

In [16]:
#Transformer
def TransformerBlock(x, num_heads=5):
    dim = x.shape[-1]

    # Multi-head attention
    attn = layers.MultiHeadAttention(num_heads=num_heads, key_dim=dim)(x, x)
    x = layers.Add()([x, attn])
    x = layers.LayerNormalization()(x)

    # Feed Forward
    ff = layers.Dense(dim, activation='relu')(x)
    ff = layers.Dense(dim)(ff)

    x = layers.Add()([x, ff])
    x = layers.LayerNormalization()(x)

    return x

In [ ]:
def ALPE(x, mask):
    # x: (B, T, C)
    # mask: (B, T, C)

    x = layers.Multiply()([x, mask])

    x = layers.Conv1D(filters=x.shape[-1], kernel_size=3, padding='same')(x)

    # Attention simple (approximation ECA)
    weights = layers.GlobalAveragePooling1D()(x)
    weights = layers.Dense(x.shape[-1], activation='sigmoid')(weights)
    weights = layers.Reshape((1, x.shape[-1]))(weights)

    x = layers.Multiply()([x, weights])

    return x

In [ ]:
def CTFusion(x):
    cnn_out = CNNBlock(x)
    trans_out = TransformerBlock(x)

    return layers.Add()([cnn_out, trans_out])

In [ ]:
def build_MCTNet(input_shape=(36, 10), num_classes=6):
    inputs = tf.keras.Input(shape=input_shape)
    mask = tf.keras.Input(shape=input_shape)

    
    x = ALPE(inputs, mask)

   
    x = CTFusion(x)
    x = layers.MaxPooling1D(pool_size=2)(x)

    x = CTFusion(x)
    x = layers.MaxPooling1D(pool_size=2)(x)

    x = CTFusion(x)

   
    x = layers.GlobalMaxPooling1D()(x)

    # Classifier
    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = tf.keras.Model(inputs=[inputs, mask], outputs=outputs)

    return model

In [ ]:
model = build_MCTNet()

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()